# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mian.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 485)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 22))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_fun = QtWidgets.QMenu(self.menubar)
        self.menu_fun.setObjectName("menu_fun")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_export_csv = QtWidgets.QAction(MainWindow)
        self.action_export_csv.setObjectName("action_export_csv")
        self.action_export_exc = QtWidgets.QAction(MainWindow)
        self.action_export_exc.setObjectName("action_export_exc")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_add = QtWidgets.QAction(MainWindow)
        self.action_add.setObjectName("action_add")
        self.action_clean = QtWidgets.QAction(MainWindow)
        self.action_clean.setObjectName("action_clean")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_add)
        self.menu_file.addAction(self.action_clean)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_export_csv)
        self.menu_file.addAction(self.action_export_exc)
        self.menu_fun.addAction(self.action)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_fun.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_fun.setTitle(_translate("MainWindow", "功能"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.action_open.setText(_translate("MainWindow", "打开"))
        self.action_export_csv.setText(_translate("MainWindow", "导出CSV"))
        self.action_export_exc.setText(_translate("MainWindow", "导出EXC"))
        self.action.setText(_translate("MainWindow", "1"))
        self.action_add.setText(_translate("MainWindow", "追加"))
        self.action_clean.setText(_translate("MainWindow", "清空列表"))
